includes:
  - base.yaml
model:
  model_name: MLPBASE
ood:
  ood_alg: ERM
  ood_param: -1.0
train:
  max_epoch: 200
  lr: 0.001
  pre_train: 50
  weight_decay: 0.0
log_file: exp_0
clean_save: true
